### PR TITLE
Apply `xo --fix` on a few files

### PR DESCRIPTION
**Pull request by daniloisr**
This is the first step to fix linter errors.

I'll be tunning XO config according to the project style.

Issue related https://github.com/OpenNeuroLab/BrainBox/issues/168

### CODE REVIEW

**Comment by daniloisr** [comment]
These changes broke the server 😭 
I'm fixing it right now

**Comment by katjaq** [comment]
amaaazing!! thank you so much!! oh my! this number was soooo shocking :D

**Comment by r03ert0** [comment]
`xo --fix` breaks brainbox in my machine (and in the server) : (
i had to roll back to an older version, and I'm linting little by little now. In particular, I'm using {"space": 4} to be coherent with our other projects (github.com/r03ert0/microdraw)

**Comment by daniloisr** [comment]
@r03ert0 you are right, `xo --fix` breaks at `no-buffer-constructor` rule, where even turning it off in the package.json it still fixed during --fix. I think that this is a bug with XO.

After running --fix I had to revert the breaking changes with the code from this commit:
https://github.com/OpenNeuroLab/BrainBox/pull/169/commits/a7ae627ff2fb4397fd3601aad5199b1f6dfcafdf

**Pull request merged**
