### PR TITLE
added 'Show' tool (default)

### PR DESCRIPTION
**Pull request by r03ert0**
added 'Show' tool (default tool instead of paint)

### CODE REVIEW

**Comment by satra** [comment]
@r03ert0 - thanks for adding this. however this doesn't allow switching planes at the correct location. it's not translating pixel coordinates to voxel coordinates properly.

**Comment by r03ert0** [comment]
for the moment, you need to send a chat message to your collaborators,
they'll then be able to click in your name which will take them to your
brain, view and slice.

**Comment by satra** [comment]
this would be just for myself, click somewhere and then click on a different orientation (sag, cor, axi) - presently it doesn't save coordinates - this is actually quite useful for detailed anatomical labeling

**Comment by r03ert0** [comment]
can you describe that with more detail ? (or a drawing! :D)

**Comment by satra** [comment]
image

http://brainbox.pasteur.fr/mri?url=http://braincatalogue.org/data/Black_rhinoceros/MRI-n4.nii.gz

(using the box annotation)

let's say i've clicked on the square point inside the red in axial orientation.

then i go click on coronal, i expect to still be in that red square. 

so anytime we click using the show tool the planes should be intersecting through the coordinate of that click. does that make sense?

**Comment by satra** [comment]
also it would be good to get a link of the current view (a url to paste into an email or sth)

**Comment by satra** [comment]
sth like:

http://brainbox.pasteur.fr/mri?url=http://braincatalogue.org/data/Black_rhinoceros/MRI-n4.nii.gz&annot=box&coord=10,23,45

**Pull request merged**
